### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by mabasic** [jurf/gnome-kmonad-toggle#2]
Thank you for this great extension.

Could you add support for Gnome 45?

**Comment by jurf** [comment]
Hey, thanks for the interest in this extension!

I have a preliminary port already running in testing on my computer, but I either introduced an error or GNOME Shell regressed, but I cannot get it to turn off with KMonad on a suspend. I have not yet had much time to fix it, but as soon as I will I will publish it. :)

**Comment by jurf** [comment]
Hey, I _think_ I managed to fix it… If you could test it, that would be great; otherwise I'll keep running it for a day or two to check if it really works properly.

**Comment by jurf** [comment]
Turns out it still did not relaunch after a lock due to a race condition (or just me misunderstanding the call order). I'll let this run until tomorrow and then publish.

**Comment by mabasic** [comment]
I haven't found the time to tinker with this yet. I've been running it from the terminal and leaving the terminal open, but would love to see this issue fixed :) Thank you for your work.

**Comment by jurf** [comment]
Uploaded the new version; sorry for the delay. It will be up as soon as it passes review. :)
